<a href="https://colab.research.google.com/github/akshaykumar2972/Netflix-Data-Analysis/blob/main/Netflix_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the libraries

In [116]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Importing the data from local file

In [117]:
df = pd.read_csv('/content/dataset.csv').drop_duplicates()
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [118]:
df.shape

(8807, 12)

In [119]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [120]:
df['added_date'] = pd.to_datetime(df['date_added'], format='mixed').dt.date

In [121]:
# Randomly compare 20 values to verify
print(df[['date_added','added_date']].sample(20))

              date_added  added_date
1032      April 16, 2021  2021-04-16
3701       June 29, 2019  2019-06-29
8145       July 15, 2018  2018-07-15
3348    November 1, 2019  2019-11-01
2544        May 11, 2020  2020-05-11
8439  September 30, 2018  2018-09-30
7163    November 1, 2017  2017-11-01
5730    November 1, 2016  2016-11-01
1966  September 20, 2020  2020-09-20
7337   September 1, 2017  2017-09-01
5939   September 1, 2013  2013-09-01
8008    October 30, 2018  2018-10-30
8090      March 15, 2018  2018-03-15
3137   December 15, 2019  2019-12-15
8125    December 1, 2020  2020-12-01
6628       June 12, 2020  2020-06-12
6085     January 1, 2019  2019-01-01
1509   December 21, 2020  2020-12-21
7252     January 1, 2020  2020-01-01
3180    December 5, 2019  2019-12-05

In [122]:
df['duration'].unique()

array(['90 min', '2 Seasons', '1 Season', '91 min', '125 min',
       '9 Seasons', '104 min', '127 min', '4 Seasons', '67 min', '94 min',
       '5 Seasons', '161 min', '61 min', '166 min', '147 min', '103 min',
       '97 min', '106 min', '111 min', '3 Seasons', '110 min', '105 min',
       '96 min', '124 min', '116 min', '98 min', '23 min', '115 min',
       '122 min', '99 min', '88 min', '100 min', '6 Seasons', '102 min',
       '93 min', '95 min', '85 min', '83 min', '113 min', '13 min',
       '182 min', '48 min', '145 min', '87 min', '92 min', '80 min',
       '117 min', '128 min', '119 min', '143 min', '114 min', '118 min',
       '108 min', '63 min', '121 min', '142 min', '154 min', '120 min',
       '82 min', '109 min', '101 min', '86 min', '229 min', '76 min',
       '89 min', '156 min', '112 min', '107 min', '129 min', '135 min',
       '136 min', '165 min', '150 min', '133 min', '70 min', '84 min',
       '140 min', '78 min', '7 Seasons', '64 min', '59 min', '139 min',
       '69 min', '148 min', '189 min', '141 min', '130 min', '138 min',
       '81 min', '132 min', '10 Seasons', '123 min', '65 min', '68 min',
       '66 min', '62 min', '74 min', '131 min', '39 min', '46 min',
       '38 min', '8 Seasons', '17 Seasons', '126 min', '155 min',
       '159 min', '137 min', '12 min', '273 min', '36 min', '34 min',
       '77 min', '60 min', '49 min', '58 min', '72 min', '204 min',
       '212 min', '25 min', '73 min', '29 min', '47 min', '32 min',
       '35 min', '71 min', '149 min', '33 min', '15 min', '54 min',
       '224 min', '162 min', '37 min', '75 min', '79 min', '55 min',
       '158 min', '164 min', '173 min', '181 min', '185 min', '21 min',
       '24 min', '51 min', '151 min', '42 min', '22 min', '134 min',
       '177 min', '13 Seasons', '52 min', '14 min', '53 min', '8 min',
       '57 min', '28 min', '50 min', '9 min', '26 min', '45 min',
       '171 min', '27 min', '44 min', '146 min', '20 min', '157 min',
       '17 min', '203 min', '41 min', '30 min', '194 min', '15 Seasons',
       '233 min', '237 min', '230 min', '195 min', '253 min', '152 min',
       '190 min', '160 min', '208 min', '180 min', '144 min', '5 min',
       '174 min', '170 min', '192 min', '209 min', '187 min', '172 min',
       '16 min', '186 min', '11 min', '193 min', '176 min', '56 min',
       '169 min', '40 min', '10 min', '3 min', '168 min', '312 min',
       '153 min', '214 min', '31 min', '163 min', '19 min', '12 Seasons',
       nan, '179 min', '11 Seasons', '43 min', '200 min', '196 min',
       '167 min', '178 min', '228 min', '18 min', '205 min', '201 min',
       '191 min'], dtype=object)

In [123]:
df['running_time'] = (pd.to_numeric(df['duration'].str.split(' ').str[0], errors='coerce').fillna(0).astype(int))

In [124]:
# Randomly compare 20 values to verify
print(df[['duration', 'running_time']].sample(20))

       duration  running_time
2025    138 min           138
1093  2 Seasons             2
6788   1 Season             1
3180     85 min            85
7720    112 min           112
5469    153 min           153
1775     93 min            93
7759   1 Season             1
2823    132 min           132
3475     81 min            81
3336  2 Seasons             2
3320     69 min            69
7336    116 min           116
6149    128 min           128
2902   1 Season             1
1985     61 min            61
1935     59 min            59
173      83 min            83
5086     71 min            71
4144   1 Season             1

In [125]:
df.drop('description', axis=1, inplace=True)

In [126]:
df.describe()

       release_year  running_time
count   8807.000000   8807.000000
mean    2014.180198     69.823095
std        8.819312     50.822520
min     1925.000000      0.000000
25%     2013.000000      2.000000
50%     2017.000000     88.000000
75%     2019.000000    106.000000
max     2021.000000    312.000000

In [127]:
df.describe(include='object')

,show_id,type,title,director,cast,country,date_added,rating,duration,listed_in,added_date
count,8807,8807,8807,6173,7982,7976,8797,8803,8804,8807,8797
unique,8807,2,8807,4528,7692,748,1767,17,220,514,1714
top,s8807,Movie,Zubaan,Rajiv Chilaka,David Attenborough,United States,"January 1, 2020",TV-MA,1 Season,"Dramas, International Movies",2020-01-01
freq,1,6131,1,19,19,2818,109,3207,1793,362,110

In [128]:
df.drop(['date_added','duration'], axis=1, inplace=True)

In [129]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country',
       'release_year', 'rating', 'listed_in', 'added_date', 'running_time'],
      dtype='object')

In [130]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
release_year       0
rating             4
listed_in          0
added_date        10
running_time       0
dtype: int64

In [131]:
df.fillna({'director': 'Unknown', 'cast': 'Unknown', 'country': 'Unknown'}, inplace=True)

In [132]:
df.dropna(axis=0, inplace=True)

In [135]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
release_year    0
rating          0
listed_in       0
added_date      0
running_time    0
dtype: int64

In [133]:
df.shape

(8793, 11)

In [134]:
df.head()

,show_id,type,title,director,cast,country,release_year,rating,listed_in,added_date,running_time
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2020,PG-13,Documentaries,2021-09-25,90
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021,TV-MA,"International TV Shows, TV Dramas, TV Mysteries",2021-09-24,2
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021,TV-MA,"Crime TV Shows, International TV Shows, TV Act...",2021-09-24,1
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021,TV-MA,"Docuseries, Reality TV",2021-09-24,1
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021,TV-MA,"International TV Shows, Romantic TV Shows, TV ...",2021-09-24,2